---
os_entropy_pkgs:
  - jitterentropy-rngd

os_entropy_services:
  - jitterentropy

os_entropy_modules: jitterentropy_rng

pwquality_pkgname: libpam-pwquality
pwquality_dest: /etc/security/pwquality.conf
cmd_recompile_initrd: depmod -ae && update-initramfs -u

os_cpu_kernel_hardening_path: /etc/default/grub.d/40_kernel_hardening.cfg
os_cpu_grub_quiet_path: /etc/default/grub.d/41_quiet.cfg
os_cpu_intel_microcode_pkgname: intel-microcode
os_cpu_amd_microcode_pkgname: amd64-microcode
