---
entropy_pkgname: haveged
service_name: haveged
pwquality_pkgname: libpwquality
pwquality_dest: /etc/pam.d/passwd
cmd_recompile_initrd: xbps-reconfigure -f $(xbps-query -l | grep {{ ansible_kernel }} | awk '{print $2}' | head -n1)
