---
- name: auto-update > installing dependencies
  ansible.builtin.package:
    name: '{{ auto_update_dependencie }}'
    state: present
  when: auto_update_dependencie is defined

- name: auto-update > add the script auto-update
  ansible.builtin.template:
    src: auto-update.sh.j2
    dest: /usr/local/bin/auto-update
    owner: root
    group: root
    mode: 0700
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Void'

- name: auto-update > add the config file
  ansible.builtin.template:
    src: auto-update-config.j2
    dest: '{{ auto_update_configfile }}'
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Void'

- name: auto-update > add a cron task
  ansible.builtin.cron:
    name: auto-update
    special_time: hourly
    user: root
    job: "/usr/local/bin/auto-update"
  notify:
    - start cron
  when: ansible_os_family == 'Void'

- name: auto-update > add the systemd service
  ansible.builtin.template:
    src: auto-update.service.j2
    dest: /usr/lib/systemd/system/auto-update.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Archlinux' and ansible_service_mgr == 'systemd'

- name: auto-update > add the systemd timer
  ansible.builtin.template:
    src: auto-update.service.timer.j2
    dest: /usr/lib/systemd/system/auto-update.timer
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Archlinux' and ansible_service_mgr == 'systemd'

- name: auto-update > enable service
  ansible.builtin.service:
    name: auto-update.timer
    state: started
    enabled: yes
  when: ansible_os_family == 'Archlinux' and ansible_service_mgr == 'systemd'
