---
# tasks file for hardening.auto
- name: Load OS-vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- import_tasks: auto-update.yml
  when: auto_update | bool
