---
- name: audit > installing dependencies
  ansible.builtin.package:
    name: '{{ os_audit_pkgs }}'

- name: audit > configuring
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    owner: root
    group: root
    mode: '0640'
  with_items:
    - regexp: '^log_format ='
      line: 'log_format = RAW'
    - regexp: '^flush ='
      line: 'flush = INCREMENTAL_ASYNC'
    - regexp: '^max_log_file_action ='
      line: 'max_log_file_action = KEEP_LOGS'
    - regexp: '^space_left ='
      line: 'space_left = 75'
    - regexp: '^action_mail_acct ='
      line: 'action_mail_acct = root'
    - regexp: '^space_left_action ='
      line: 'space_left_action = SYSLOG'
    - regexp: '^admin_space_left ='
      line: 'admin_space_left = 50'
    - regexp: '^admin_space_left_action ='
      line: 'admin_space_left_action = SUSPEND'
    - regexp: '^disk_full_action ='
      line: 'disk_full_action = SUSPEND'
    - regexp: '^disk_error_action ='
      line: 'disk_error_action = SUSPEND'

- name: audit > enabling service
  ansible.builtin.service:
    name: '{{ os_audit_service_name }}'
    state: started
    enabled: true
