---
- name: Ensure /etc/systemd/coredump.conf.d directory exists.
  ansible.builtin.file:
    path: /etc/systemd/coredump.conf.d
    state: directory
    mode: 0755
  when: ansible_service_mgr == 'systemd'

- name: coredump on /etc/systemd/coredump.conf.d/disable.conf
  ansible.builtin.copy:
    src: systemd-coredump
    dest: /etc/systemd/coredump.conf.d/disable.conf
    mode: 0644
  when: ansible_service_mgr == 'systemd'

- name: coredump on /etc/security/limits.conf
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf 
    regexp: '^\* hard core'
    line: '* hard core 0'
