---
# tasks file for cmdline
- name: mount /boot
  ansible.builtin.shell: '{{ os_mount_boot_cmd }}'
  when: os_mount_boot_cmd is defined

# https://wiki.debian.org/Microcode
- name: Add microcode repository.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - deb http://deb.debian.org/debian bullseye main contrib non-free
    - deb http://security.debian.org/debian-security bullseye-security main contrib non-free
    - deb http://deb.debian.org/debian bullseye-updates main contrib non-free
  when: ansible_os_family == 'Debian'

- name: Update Pacman cache
  community.general.pacman:
    update_cache: true
  when: ansible_os_family == 'Archlinux'

- name: install Intel microcode
  ansible.builtin.package:
    name: '{{ os_cpu_intel_microcode_pkgname }}'
    state: latest
  when: ansible_processor[1] == 'GenuineIntel'

- name: install Amd microcode
  ansible.builtin.package:
    name: '{{ os_cpu_amd_microcode_pkgname }}'
    state: latest
  when: ansible_processor[1] == 'AuthenticAMD'
