---
- name: Grub > hardening cmdline by template
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.template', 'grub-cmdline.j2') }}"
    marker: "\n# {mark} Configured with Ansible"
    path: "{{ os_cpu_kernel_hardening_path }}"
