---
# Linux hardened is only available on x86_64 and arm64
- name: Kernel > installing The Good Kernel
  ansible.builtin.package:
    name: "{{ os_linux_hardened_pkgs }}"
    state: present
  when: os_linux_hardened_pkgs is defined and ansible_facts["userspace_architecture"] == 'x86_64'

- name: Kernel > removing older kernel packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ os_linux_pkgs_list }}"
  when: os_linux_pkgs_list is defined and ansible_facts["userspace_architecture"] == 'x86_64'
