---
- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: search for Grub
  ansible.builtin.shell: hash grub-mkconfig 2>/dev/null
  register: has_grub
  ignore_errors: true

- import_tasks: secure-time-sync.yml
  when: os_fix_ntp | bool

- import_tasks: cpu.yml
  become: true
  notify:
    - update-grub
  when: os_fix_cpu_microcode | bool

- import_tasks: cmdline_grub.yml
  when: os_fix_cmdline_grub | bool

- import_tasks: modprobe.yml
  when: os_fix_modprobe | bool

- import_tasks: permissions.yml
  when: os_fix_permissions | bool

- import_tasks: sysctl.yml
  become: true
  when: os_fix_sysctl | bool

- import_tasks: pam.yml
  when: os_fix_pam | bool

- name: Entropy {{ entropy_pkgname }}
  package:
    name: '{{ entropy_pkgname }}'
    state: present
  notify:
    - Start Entropy Service
    - Load module jitterentropy
    - update-initrd

- name: Hidepid
  import_tasks: hidepid.yml
  when: os_fix_hidepid

- import_tasks: core_dumps.yml
  become: true
  when: os_fix_core_dumps | bool

- import_tasks: login_defs.yml
  when: os_fix_login_defs | bool

- name: umask to {{ os_umask }}
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: '^umask'
    line: "umask {{ os_umask }}"
