---
- name: Debug
  ansible.builtin.debug:
    msg:
      - "cmd: '{{ cmd_recompile_initrd }}'"

- name: Unload
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
    - pcspkr
    - mei_pxp
    - mei_hdcp
    - mei_txe
    - mei-me
    - mei
  ignore_errors: true

- name: Unload bluetooth
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - hci_vhci
    - hci_uart
    - btusb
    - btbcm
    - btqca
    - btmtk
    - btrtl
    - bluetooth
  when: os_modprobe_blacklist_bluetooth | bool
  ignore_errors: true

- name: Modprobe > {{ os_modprobe_dir }}/mods-config.conf
  ansible.builtin.template:
    src: modprobe-config.j2
    dest: "{{ os_modprobe_dir }}/mods-config.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - update-initrd

- name: Modprobe > {{ os_modprobe_dir }}/mods-uninstall.conf
  ansible.builtin.template:
    src: modprobe-uninstall.j2
    dest: "{{ os_modprobe_dir }}/mods-uninstall.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - update-initrd

- name: Modprobe > {{ os_modprobe_dir }}/mods-blacklist.conf
  ansible.builtin.template:
    src: modprobe-blacklist.j2
    dest: "{{ os_modprobe_dir }}/mods-blacklist.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - update-initrd
