---
- name: debug
  ansible.builtin.debug:
    msg:
      - "cmd: '{{ cmd_recompile_initrd }}'"

- name: unload
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
    - pcspkr
    - mei_pxp
    - mei_hdcp
    - mei_txe
    - mei-me
    - mei

- name: unload bluetooth
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - hci_vhci
    - hci_uart
    - btusb
    - bluetooth
  when: os_modprobe_remove_bluetooth | bool

- name: modprobe > remove previous files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ os_modprobe_dir }}/30_config.conf'
    - '{{ os_modprobe_dir }}/31_uninstall.conf'
    - '{{ os_modprobe_dir }}/32_blacklist.conf'

- name: modprobe > {{ os_modprobe_dir }}/mods-config.conf
  ansible.builtin.template:
    src: modprobe-config.j2
    dest: '{{ os_modprobe_dir }}/mods-config.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd

- name: modprobe > {{ os_modprobe_dir }}/mods-uninstall.conf
  ansible.builtin.template:
    src: modprobe-uninstall.j2
    dest: '{{ os_modprobe_dir }}/mods-uninstall.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd

- name: modprobe > {{ os_modprobe_dir }}/mods-blacklist.conf
  ansible.builtin.template:
    src: modprobe-blacklist.j2
    dest: '{{ os_modprobe_dir }}/mods-blacklist.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd
