---
- name: debug
  ansible.builtin.debug:
    msg:
      - "cmd: '{{ cmd_recompile_initrd }}'"

- name: unload
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
    - pcspkr
    - mei_pxp
    - mei_hdcp
    - mei_txe
    - mei-me
    - mei

- name: unload bluetooth
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - hci_vhci
    - hci_uart
    - btusb
    - bluetooth
  when: os_modprobe_remove_bluetooth | bool

- name: configure > {{ os_modprobe_config_path }}
  ansible.builtin.template:
    src: modprobe-config.j2
    dest: '{{ os_modprobe_config_path }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd

- name: uninstall > {{ os_modprobe_uninstall_path }}
  ansible.builtin.template:
    src: modprobe-uninstall.j2
    dest: '{{ os_modprobe_uninstall_path }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd

- name: blacklist > {{ os_modprobe_blacklist_path }}
  ansible.builtin.template:
    src: modprobe-blacklist.j2
    dest: '{{ os_modprobe_blacklist_path }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - update-initrd
