---
- name: modules > disable obscure network protocol
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
    - pcspkr
    - mei_pxp
    - mei_hdcp
    - mei_txe
    - mei-me
    - mei

- name: modules > disable bluetooth
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - hci_vhci
    - hci_uart
    - btusb
    - bluetooth
  when: os_modules_disable_bluetooth | bool

- name: modules > saving current modules used
  ansible.builtin.shell:
    cat /proc/modules | sort | awk '{print $1}' > {{ os_modules_load_path }}
  notify:
    - update-initrd
  when: os_modules_load_path is defined

- name: modules > enable kernel.modules_disabled
  ansible.posix.sysctl:
    name: 'kernel.modules_disabled'
    value: '1'
    sysctl_file: '{{ os_sysctl_kernel_conf }}'
    reload: no
  notify:
    - update-initrd
