---
- name: modules > search efi system
  ansible.builtin.stat:
    path: /sys/firmware/efi
  register: efi_installed

- name: modules > setting efi fact
  ansible.builtin.set_fact:
    efi_installed: efi_installed.stat.isdir is defined and efi_installed.isdir

- name: modules > disable obscure network protocol
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
    - pcspkr
    - mei_pxp
    - mei_hdcp
    - mei_txe
    - mei-me
    - mei

- name: modules > disable bluetooth
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - hci_vhci
    - hci_uart
    - btusb
    - bluetooth
  when: os_modules_disable_bluetooth | bool

- name: modules > saving current modules used
  ansible.builtin.shell:
    cat /proc/modules | sort | awk '{print $1}' > {{ os_modules_load_path }}
  notify:
    - update-initrd
  when: os_modules_load_path is defined

- name: modules > add vfat for efi
  ansible.builtin.lineinfile:
    dest: '{{ os_modules_load_path }}'
    line: '{{ item }}'
  with_items:
    - vfat
    - nls_cp437
    - nls_iso8859_1
  when: efi_installed

- name: modules > disable audio
  ansible.builtin.lineinfile:
    dest: '{{ os_modules_load_path }}'
    line: '{{ item }}'
    state: absent
  with_items: os_modules_items_audio
  when: os_modules_disable_audio | bool

# modprobe --show-depends uvcvideo
- name: modules > disable camera
  ansible.builtin.lineinfile:
    dest: '{{ os_modules_load_path }}'
    line: '{{ item }}'
    state: absent
  with_items: os_modules_items_camera
  when: os_modules_disable_camera | bool

- name: modules > disable btrfs
  ansible.builtin.lineinfile:
    dest: '{{ os_modules_load_path }}'
    line: '{{ item }}'
    state: absent
  with_items:
    - xor
    - raid6_pq
    - btrfs
  when: os_modules_disable_btrfs | bool

- name: modules > enable kernel.modules_disabled
  ansible.posix.sysctl:
    name: 'kernel.modules_disabled'
    value: '1'
    sysctl_file: '{{ os_sysctl_kernel_conf }}'
    reload: no
  notify:
    - update-initrd
