---
- name: Installing pwquality
  ansible.builtin.package:
    name: "{{ pwquality_pkgname }}"
    state: present

- name: Configure pwquality
  ansible.builtin.template:
    src: pwquality.j2
    dest: "{{ pwquality_dest }}"
