---
- name: installing pwquality
  ansible.builtin.package:
    name: '{{ pwquality_pkgname }}'
    state: present

- name: configure pwquality
  ansible.builtin.template:
    src: pwquality.j2
    dest: '{{ pwquality_dest }}'
  when: ansible_os_family != 'Void' # pwquality doesn't work yet on void musl
