---
- name: Fix directory permissions
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  with_items:
    - /boot
    - /usr/src
    - /usr/lib/modules
    - '{{ ansible_user_dir }}'
