---
# tasks file for secure_time_sync
- name: Sts > downloading secure-time-sync
  ansible.builtin.get_url:
    dest: /usr/local/bin/secure-time-sync
    url: https://raw.githubusercontent.com/szorfein/secure-time-sync/main/secure-time-sync.sh
    checksum: sha256:9dde9b9cba77930d66d1a82651c377b5b7ea2bbc40f02e3490e575bac3dc5a96
    mode: "0755"

- name: Sts > installing dependencies
  ansible.builtin.package:
    name: curl
    state: present

- ansible.builtin.include_tasks: secure-time-sync-apparmor.yml
  when: ansible_facts['apparmor'].status == 'enabled'

# TODO: remove secure-time-sync here on the next release
- name: Sts > Disabling systemd NTP protocol services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - systemd-timesyncd
    - secure-time-sync
  ignore_errors: true
  #when: ansible_facts['service_mgr'] == 'systemd'

- name: Sts > Disabling ntp using timedatectl
  ansible.builtin.command: timedatectl set-ntp 0
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Sts > Removing old cron job
  ansible.builtin.cron:
    name: "secure-time-sync for reboot"
    state: absent

- name: Sts > Adding a cron job all the 30 minutes
  ansible.builtin.cron:
    name: "Update time with https"
    job: "/usr/local/bin/secure-time-sync"
    minute: "*/30"
    state: present
    user: root
