---
# defaults file for szorfein.hardening.os
os_fix_core_dumps: true
os_fix_login_defs: true
os_fix_modprobe: true
os_fix_ntp: true
os_fix_pam: true
os_fix_permissions: true
os_fix_sysctl: true
os_fix_cpu: true

os_umask: '027'

# pass aging controls
os_auth_pass_min_days: 7
os_auth_pass_max_days: 180

os_auth_crypt_rounds: 20000

os_sysctl_kernel_conf: '/etc/sysctl.d/kernel.conf'
os_sysctl_network_conf: '/etc/sysctl.d/network.conf'
os_sysctl_userspace_conf: '/etc/sysctl.d/userspace.conf'
os_sysctl_kernel_rules: true
os_sysctl_network_rules: true
os_sysctl_userspace_rules: true

os_modules: false
os_modules_disable_bluetooth: false
os_modules_disable_cdrom: true

os_modprobe_config_path: /etc/modprobe.d/30_config.conf
os_modprobe_uninstall_path: /etc/modprobe.d/31_uninstall.conf
os_modprobe_blacklist_path: /etc/modprobe.d/32_blacklist.conf
