---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: Start Entropy Service
  ansible.builtin.service:
    name: '{{ os_entropy_service_name }}'
    state: started
    enabled: true
  when: os_entropy_service_name is defined

- name: Load module jitterentropy
  ansible.builtin.template:
    src: entropy_mod.j2
    dest: /usr/lib/modules-load.d/jitterentropy.conf
  when: entropy_module is defined

- name: update-initrd
  become: true
  ansible.builtin.shell: '{{ cmd_recompile_initrd }}'
  when: cmd_recompile_initrd is defined and
        (not os_fix_kernel and os_linux_hardened_cmd_initrd is undefined)

- name: update-hardened-initrd
  become: true
  ansible.builtin.shell: '{{ os_linux_hardened_cmd_initrd }}'
  when: os_linux_hardened_cmd_initrd is defined

- name: update-grub
  become: true
  ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg
  when: has_grub is succeeded

- name: Start Tor
  ansible.builtin.service:
    name: tor
    state: started
    enabled: true

- name: Enable Cronie
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: true

- name: Enable Sts
  ansible.builtin.service:
    name: secure-time-sync
    state: started
    enabled: true

- name: Enable Sts with Tor
  ansible.builtin.service:
    name: secure-time-sync-with-tor
    state: started
    enabled: true

- name: Restart Tor
  ansible.builtin.service:
    name: tor
    state: restarted

- name: auditd reload rules
  become: true
  ansible.builtin.command: augenrules --load
